### PR TITLE
Alias to get all aliases

### PR DESCRIPTION
**Pull request by haisi**
Yo dawg I heard you like aliases...

### CODE REVIEW

**Comment by gggritso** [comment]
Love it! How about `!git config --get-regexp alias | sed s/alias.//` to clean up the output?

**Comment by haisi** [comment]
Good idea! We could go further by making the output a little bit more pretty:
`!git config --get-regexp alias | sed 's/alias.//' | sed 's/ / \t /'`
Would print the alias name and the actual command separated by a tab. This way you can clearly see what the actual alias is and what is does.  
The problem with this solution is that the '\t' separator isn't ideal, but the 'column'-command isn't available on windows by default. There is `pr` which I couln't get to work properply yet.

I probably won't be able to fix it right now, so I'll just update the pull-request with your input.

**Comment by gggritso** [comment]
Interesting note on portability, thanks! Last suggestion from me is to just add a colon instead of worrying about the tab: `git config --get-regexp alias | sed "s/alias\.\([A-Za-z]*\)/\1: /"`. How’s that?

```
filetrail:  log --follow -p -w
mergetrail:  log --ancestry-path --merges
unmerged:  diff --name-only --diff-filter=U
```

**Comment by gggritso** [comment]
Totally forgot all about this! Updated the syntax and merged :)

**Pull request merged**
